# Generated by Django 2.2.16 on 2025-06-13 02:09

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name': 'Закладка', 'verbose_name_plural': 'Закладки'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Список покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
        migrations.RemoveField(
            model_name='dish',
            name='text',
        ),
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.TextField(default='Описание не указано', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='app.Dish', verbose_name='Блюдо'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимум одна минута'), django.core.validators.MaxValueValidator(1440, message='Не больше 24 часов')], verbose_name='Время приготовления (минуты)'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Повар'),
        ),
        migrations.AlterField(
            model_name='label',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=7, samples=None, verbose_name='Цвет метки'),
        ),
        migrations.AlterField(
            model_name='label',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Идентификатор метки (slug)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(max_length=200, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='producttodish',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Введите положительное число')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='producttodish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producttodish', to='app.Dish', verbose_name='Блюдо'),
        ),
        migrations.AlterField(
            model_name='producttodish',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product', verbose_name='Продукт'),
        ),
    ]
